"""STATISTICAL checks (04_CHECK_CATALOG.md §STATISTICAL).

Uses Welford's online algorithm (checks/welford.py) for numerically stable,
streaming mean/std recomputation — never loads full data into memory per
05_ENGINEERING_STANDARDS.md §6.

  STATISTICAL.STATS_MATCH_DATA       (FAIL) — global stats.json vs recomputed
  STATISTICAL.PER_EPISODE_STATS_MATCH (WARN) — per-episode stats vs recomputed
  STATISTICAL.VALUE_SANITY           (WARN→FAIL) — degenerate column detection

Tolerance calibration (per 07_EVALUATION_AND_ACCURACY.md §6):
  Method: measured on synthetic fixtures where stats.json is generated by the
  same float32 arithmetic as the data writer.

  Step 1 — Clean-data floor:
    Built a 3-episode, 4-frame/episode fixture with float32 timestamps
    [0, 1/30, 2/30, 3/30] per episode. Stats.json mean is computed by the
    builder; Welford recomputes the same values from float32 Arrow data.
    Measured max relative deviation: < 1e-6 (well under float32 machine
    epsilon ~6e-8 times data scale, because the numbers are small and
    the dataset tiny — the key point is deviation is << 1e-4 on clean data).

  Step 2 — Corrupted-data signal:
    Modified stats.json mean for 'timestamp' by +0.1 on data whose true mean
    is ~0.05 (a ~200% relative error). Measured relative deviation: ~2.0.

  Step 3 — Threshold selection:
    Gap between clean (< 1e-4) and corrupted (>> 0.01) is over 100x.
    Setting rtol=1e-4 (relative tolerance) gives zero false positives on
    clean float32 data and catches any meaningful stat divergence.
    Setting atol=1e-6 as an absolute floor prevents false positives for
    near-zero features (e.g., action=0 throughout, stored mean ~0) where
    relative tolerance would be undefined or unstable.

  Calibration data: synthetic trajlens fixtures in tests/fixtures/builders.py
  (build_v3_dataset, float32 timestamp column).  Re-calibrate if the lerobot
  writer changes its stats computation or storage precision.
"""

from __future__ import annotations

import math

import structlog

from trajlens.checks.protocol import Check, CheckContext, CheckResult, Severity
from trajlens.checks.registry import registry
from trajlens.checks.utils import (
    MAX_PER_EPISODE_ENTRIES,
    MAX_SAMPLE_MESSAGES,
    format_violation_count,
)
from trajlens.checks.welford import WelfordAccumulator
from trajlens.model.canonical import CanonicalDataset

log = structlog.get_logger(__name__)

# Calibrated tolerance for mean/std comparison (see module docstring for method).
# Relative tolerance: max(|stored - recomputed|) / max(1, |recomputed|) <= rtol
# Absolute floor: if |recomputed| < atol_floor, use absolute comparison instead.
# Calibration: clean fixture max deviation < 1e-6; corrupt fixture deviation > 0.01.
# Threshold 1e-4 provides > 100x margin above the clean-data noise floor.
_STATS_RTOL: float = 1e-4  # relative tolerance
_STATS_ATOL: float = 1e-6  # absolute floor for near-zero features


def _relative_error(stored: float, recomputed: float) -> float:
    """Symmetric relative error with absolute floor for near-zero denominators."""
    denom = max(abs(recomputed), _STATS_ATOL)
    return abs(stored - recomputed) / denom


def _flatten_row_value(val: object) -> list[float]:
    """Flatten one row's Arrow-derived value to a flat list of per-element floats.

    A scalar feature's row value is a bare number -> a single-element list.
    A multi-dim feature's row value is a (possibly nested) Python list from
    Arrow's to_pylist() -> flattened depth-first, in the same row-major order
    Arrow itself serializes a multi-dim feature in. None (a missing/null
    cell) becomes [nan] so it still occupies its position rather than being
    silently dropped, matching WelfordAccumulator.update()'s own NaN handling.
    """
    if val is None:
        return [math.nan]
    if isinstance(val, list | tuple):
        flat: list[float] = []
        for item in val:
            flat.extend(_flatten_row_value(item))
        return flat
    if isinstance(val, int | float):
        # bool is an int subclass (True/False -> 1.0/0.0), covered here too.
        return [float(val)]
    # Arrow's to_pylist() only yields int/float/bool/str/None/list for the
    # numeric-dtype columns this is called on (dtype not in ("video",
    # "string")). Any other type reaching here means the declared dtype
    # disagrees with what is actually stored -- SEMANTIC.FEATURE_DIMENSIONALITY
    # and STRUCTURAL.SCHEMA_CONSISTENCY are the checks responsible for that
    # class of finding, so this treats it as an unusable observation (NaN)
    # rather than raising and aborting the whole check.
    return [math.nan]


def _stream_feature_columns(
    ds: CanonicalDataset,
    episodes: list[object] | None = None,
) -> dict[str, list[WelfordAccumulator]]:
    """Stream all non-video features across episodes, updating per-element accumulators.

    Returns a dict mapping feature_name -> one WelfordAccumulator per element
    position (length 1 for a scalar feature, length N for an N-wide
    multi-dim feature such as a 7-DoF ``action``). This mirrors how
    meta/stats.json itself stores mean/std/min/max — one number per element
    for a scalar feature, one list of N numbers for an N-wide feature — so a
    caller can compare like-for-like instead of folding every dimension into
    a single pooled number (which manufactures FAIL findings on any dataset
    with a multi-dim feature; see the regression fixture this change adds).
    Operates in O(1) RAM per row group read.
    """
    from trajlens.model.canonical import EpisodeRecord

    accumulators: dict[str, list[WelfordAccumulator]] = {}
    numeric_features = [
        name for name, spec in ds.features.items() if spec.dtype not in ("video", "string")
    ]

    target_episodes: list[EpisodeRecord]
    if episodes is None:
        target_episodes = list(ds)
    else:
        target_episodes = [ep for ep in episodes if isinstance(ep, EpisodeRecord)]

    for episode in target_episodes:
        pf = ds.parquet_shard_for_episode(episode)
        # Read only the columns we need; this keeps RAM proportional to
        # row-group size, not total dataset size.
        available = [f for f in numeric_features if f in pf.schema_arrow.names]
        if not available:
            continue
        table = pf.read(columns=["episode_index", *available])  # type: ignore[no-untyped-call]
        ep_col = table.column("episode_index").to_pylist()

        for feat_name in available:
            col_list = table.column(feat_name).to_pylist()
            for row_idx, ep_val in enumerate(ep_col):
                if ep_val != episode.episode_index:
                    continue
                flat = _flatten_row_value(col_list[row_idx])
                accs = accumulators.get(feat_name)
                if accs is None:
                    accs = [WelfordAccumulator() for _ in range(len(flat))]
                    accumulators[feat_name] = accs
                elif len(accs) < len(flat):
                    # A ragged/malformed row wider than any seen so far -- extend
                    # rather than crash; SEMANTIC.FEATURE_DIMENSIONALITY is the
                    # check responsible for flagging width inconsistency itself.
                    accs.extend(WelfordAccumulator() for _ in range(len(flat) - len(accs)))
                for i, scalar in enumerate(flat):
                    accs[i].update(scalar)

    return accumulators


# ---------------------------------------------------------------------------
# STATISTICAL.STATS_MATCH_DATA
# ---------------------------------------------------------------------------


class _StatsMatchDataCheck:
    id = "STATISTICAL.STATS_MATCH_DATA"
    severity = Severity.FAIL
    category = "STATISTICAL"
    requires_video = False
    thread_safe = True

    def run(self, ds: CanonicalDataset, ctx: CheckContext) -> CheckResult:
        resolver_handle = getattr(ds._resolver, "handle", None)
        if (
            not ctx.deep
            and resolver_handle is not None
            and getattr(resolver_handle, "repo_id", None) is not None
        ):
            return CheckResult(
                check_id=self.id,
                severity=Severity.INFO,
                message=(
                    "Skipped STATISTICAL.STATS_MATCH_DATA for Hub dataset "
                    "(too slow over HTTP). Use --deep to verify stats."
                ),
            )

        stored_stats = ds.stats.load()

        if stored_stats is None:
            return CheckResult(
                check_id=self.id,
                severity=Severity.INFO,
                message="No meta/stats.json found — global stats check skipped.",
            )

        violations: list[str] = []

        # Stream all episodes and accumulate per-element Welford stats: one
        # accumulator per element position, not one pooled accumulator per
        # feature. A multi-dim feature's dimensions are independent signals
        # with independent stored mean/std entries -- pooling them together
        # (the pre-fix behavior) compared every stored per-dimension value
        # against the same cross-dimension average and manufactured a FAIL
        # on any dataset with a multi-dim feature such as a 7-DoF action.
        accumulators = _stream_feature_columns(ds)

        for feat_name, accs in accumulators.items():
            feat_stored = stored_stats.get(feat_name)
            if feat_stored is None:
                # Feature has data but no stats entry — skip rather than FAIL;
                # stats.json may intentionally omit some features.
                continue

            stored_mean_raw = feat_stored.get("mean")
            stored_std_raw = feat_stored.get("std")

            stored_means = _flatten_to_scalars(stored_mean_raw)
            stored_stds = _flatten_to_scalars(stored_std_raw)

            if stored_means is None or stored_stds is None:
                continue

            if len(stored_means) != len(accs) or len(stored_stds) != len(accs):
                violations.append(
                    f"feature {feat_name!r}: stored stats have "
                    f"{len(stored_means)} mean / {len(stored_stds)} std element(s) "
                    f"but the data has {len(accs)} element(s) per row "
                    f"(dimension count mismatch)"
                )
                continue

            # Element i of stored_means/stored_stds is compared against
            # accs[i] -- its own dimension's accumulator, never a different
            # dimension's or a cross-dimension pooled one.
            for i, (sm, ss, acc) in enumerate(zip(stored_means, stored_stds, accs, strict=True)):
                idx_suffix = f"[{i}]" if len(accs) > 1 else ""
                mean_err = _relative_error(sm, acc.mean)
                std_err = _relative_error(ss, acc.std)

                if mean_err > _STATS_RTOL:
                    violations.append(
                        f"feature {feat_name!r}{idx_suffix}: stored mean={sm:.8g} "
                        f"vs recomputed={acc.mean:.8g} "
                        f"(relative error {mean_err:.2e} > rtol={_STATS_RTOL:.2e})"
                    )
                if std_err > _STATS_RTOL:
                    violations.append(
                        f"feature {feat_name!r}{idx_suffix}: stored std={ss:.8g} "
                        f"vs recomputed={acc.std:.8g} "
                        f"(relative error {std_err:.2e} > rtol={_STATS_RTOL:.2e})"
                    )

        if violations:
            return CheckResult(
                check_id=self.id,
                severity=Severity.FAIL,
                message=(
                    f"Global stats.json diverges from recomputed values "
                    f"({len(violations)} issue(s)): {violations[0]}"
                ),
                details={
                    "violations": violations,
                    "rtol": _STATS_RTOL,
                    "atol": _STATS_ATOL,
                },
            )
        return CheckResult(
            check_id=self.id,
            severity=Severity.INFO,
            message=(
                f"Global stats.json matches recomputed Welford values within tolerance "
                f"(rtol={_STATS_RTOL:.0e}, atol={_STATS_ATOL:.0e})."
            ),
        )


def _flatten_to_scalars(value: object) -> list[float] | None:
    """Flatten a stats value (scalar, list, nested list) to a flat list of floats."""
    if value is None:
        return None
    if isinstance(value, int | float):
        return [float(value)]
    if isinstance(value, list):
        flat: list[float] = []
        for item in value:
            sub = _flatten_to_scalars(item)
            if sub is not None:
                flat.extend(sub)
        return flat if flat else None
    return None


STATS_MATCH_DATA: Check = _StatsMatchDataCheck()
registry.register(STATS_MATCH_DATA)


# ---------------------------------------------------------------------------
# STATISTICAL.PER_EPISODE_STATS_MATCH
# ---------------------------------------------------------------------------
# v2.1: per-episode stats live in meta/episodes_stats.jsonl
# v3.0: per-episode stats are inline columns in meta/episodes/*.parquet
#       with column names like "stats/timestamp/mean", "stats/timestamp/std", etc.
#       (per 03_DATA_FORMAT_SPEC.md §2 [verified, M3])


class _PerEpisodeStatsMatchCheck:
    id = "STATISTICAL.PER_EPISODE_STATS_MATCH"
    severity = Severity.WARN
    category = "STATISTICAL"
    requires_video = False
    thread_safe = True

    def run(self, ds: CanonicalDataset, ctx: CheckContext) -> CheckResult:
        resolver_handle = getattr(ds._resolver, "handle", None)
        if (
            not ctx.deep
            and resolver_handle is not None
            and getattr(resolver_handle, "repo_id", None) is not None
        ):
            return CheckResult(
                check_id=self.id,
                severity=Severity.INFO,
                message=(
                    "Skipped STATISTICAL.PER_EPISODE_STATS_MATCH for Hub dataset "
                    "(too slow over HTTP). Use --deep to verify stats."
                ),
            )

        from trajlens.sources.version import DatasetVersion

        if ds.version is DatasetVersion.V2_0:
            return CheckResult(
                check_id=self.id,
                severity=Severity.INFO,
                message="v2.0 datasets do not carry per-episode stats — check skipped.",
            )

        # Every episode is scanned so total_violations is the TRUE total;
        # `violations` retains only a bounded sample for display. See
        # checks/utils.py for why these must stay separate. Note this means a
        # failing dataset now costs the same full scan a clean one always
        # did (this check never broke early when nothing was wrong), rather
        # than bailing at the display cap -- the worst case is unchanged.
        violations: list[str] = []
        total_violations = 0
        per_episode: dict[int, str] = {}

        def record(finding: str) -> None:
            nonlocal total_violations
            total_violations += 1
            if len(violations) < MAX_SAMPLE_MESSAGES:
                violations.append(finding)

        for episode in ds:
            # Recompute per-episode stats via Welford streaming.
            accumulators = _stream_feature_columns(ds, episodes=[episode])
            ep_findings: list[str] = []

            if ds.version is DatasetVersion.V3_0:
                # Per-episode stats are inline in the episode metadata Parquet.
                ep_stored = _load_v3_episode_stats(ds, episode.episode_index)
                if ep_stored is None:
                    continue  # No stats columns in this shard — skip.

                for feat_name, accs in accumulators.items():
                    mean_key = f"stats/{feat_name}/mean"
                    std_key = f"stats/{feat_name}/std"
                    if mean_key not in ep_stored and std_key not in ep_stored:
                        continue

                    stored_mean_raw = ep_stored.get(mean_key)
                    stored_std_raw = ep_stored.get(std_key)

                    stored_means = _flatten_to_scalars(stored_mean_raw)
                    stored_stds = _flatten_to_scalars(stored_std_raw)

                    if stored_means is None or stored_stds is None:
                        continue
                    if len(stored_means) != len(accs) or len(stored_stds) != len(accs):
                        finding = (
                            f"episode {episode.episode_index} feature {feat_name!r}: "
                            f"dimension count mismatch ({len(stored_means)} stored vs "
                            f"{len(accs)} in data)"
                        )
                        record(finding)
                        ep_findings.append(finding)
                        continue

                    # sm/ss/acc are the SAME dimension i's stored value and
                    # recomputed accumulator -- never a different dimension's.
                    for sm, ss, acc in zip(stored_means, stored_stds, accs, strict=True):
                        if _relative_error(sm, acc.mean) > _STATS_RTOL:
                            finding = (
                                f"episode {episode.episode_index} feature {feat_name!r}: "
                                f"stored mean={sm:.8g} vs recomputed={acc.mean:.8g}"
                            )
                            record(finding)
                            ep_findings.append(finding)
                        if _relative_error(ss, acc.std) > _STATS_RTOL:
                            finding = (
                                f"episode {episode.episode_index} feature {feat_name!r}: "
                                f"stored std={ss:.8g} vs recomputed={acc.std:.8g}"
                            )
                            record(finding)
                            ep_findings.append(finding)

            elif ds.version is DatasetVersion.V2_1:
                # v2.1 episodes_stats.jsonl is loaded by the source layer;
                # it's available in canonical form via the StatsHandle.
                # For v2.1, per-episode stats are stored in episodes_stats.jsonl
                # as {"episode_index": N, "stats": {...}}.
                ep_stored_v2 = _load_v2_episode_stats(ds, episode.episode_index)
                if ep_stored_v2 is None:
                    continue

                for feat_name, accs in accumulators.items():
                    feat_stored = ep_stored_v2.get(feat_name)
                    if feat_stored is None or not isinstance(feat_stored, dict):
                        continue

                    stored_means = _flatten_to_scalars(feat_stored.get("mean"))
                    stored_stds = _flatten_to_scalars(feat_stored.get("std"))

                    if stored_means is None or stored_stds is None:
                        continue
                    if len(stored_means) != len(accs) or len(stored_stds) != len(accs):
                        finding = (
                            f"episode {episode.episode_index} feature {feat_name!r}: "
                            f"dimension count mismatch ({len(stored_means)} stored vs "
                            f"{len(accs)} in data)"
                        )
                        record(finding)
                        ep_findings.append(finding)
                        continue

                    for sm, ss, acc in zip(stored_means, stored_stds, accs, strict=True):
                        if _relative_error(sm, acc.mean) > _STATS_RTOL:
                            finding = (
                                f"episode {episode.episode_index} feature {feat_name!r}: "
                                f"stored mean={sm:.8g} vs recomputed={acc.mean:.8g}"
                            )
                            record(finding)
                            ep_findings.append(finding)
                        if _relative_error(ss, acc.std) > _STATS_RTOL:
                            finding = (
                                f"episode {episode.episode_index} feature {feat_name!r}: "
                                f"stored std={ss:.8g} vs recomputed={acc.std:.8g}"
                            )
                            record(finding)
                            ep_findings.append(finding)

            if ep_findings and len(per_episode) < MAX_PER_EPISODE_ENTRIES:
                per_episode[episode.episode_index] = " | ".join(ep_findings)

        if total_violations:
            return CheckResult(
                check_id=self.id,
                severity=Severity.WARN,
                message=(
                    f"Per-episode stats diverge from recomputed values "
                    f"({format_violation_count(total_violations, violations)}): "
                    f"{violations[0]}"
                ),
                details={
                    "violations": violations,
                    "total_violations": total_violations,
                    "affected_episodes": len(per_episode),
                    "rtol": _STATS_RTOL,
                },
                per_episode=per_episode or None,
            )
        return CheckResult(
            check_id=self.id,
            severity=Severity.INFO,
            message="Per-episode stats match recomputed values within tolerance.",
        )


def _load_v3_episode_stats(ds: CanonicalDataset, episode_index: int) -> dict[str, object] | None:
    """Load per-episode stats columns from v3.0 episode metadata Parquet."""
    from trajlens.model.canonical import EpisodeRecord

    # Find the episode record to resolve the metadata shard.
    ep: EpisodeRecord | None = None
    for e in ds:
        if e.episode_index == episode_index:
            ep = e
            break
    if ep is None:
        return None

    # The episode metadata shard is the same shard the ShardResolver uses for
    # parquet_shard_for_episode — but that returns the *data* shard, not the
    # metadata shard.  We need to read the meta/episodes shard directly.
    # The CanonicalDataset doesn't expose the metadata shard path directly,
    # so we use the StatsHandle root to locate it.
    import pyarrow.parquet as pq

    from trajlens.sources.paths import safe_join

    # Walk all meta/episodes shards looking for this episode_index.
    meta_episodes_dir = safe_join(ds.stats.root, "meta", "episodes")
    if not meta_episodes_dir.is_dir():
        return None

    for chunk_dir in sorted(meta_episodes_dir.iterdir()):
        if not chunk_dir.is_dir():
            continue
        for shard_file in sorted(chunk_dir.glob("*.parquet")):
            try:
                tbl = pq.read_table(str(shard_file))  # type: ignore[no-untyped-call]
            except Exception as exc:
                log.debug("episode_stats_shard_unreadable", path=str(shard_file), exc=str(exc))
                continue
            if "episode_index" not in tbl.schema.names:
                continue
            ep_col = tbl.column("episode_index").to_pylist()
            for row_idx, ep_val in enumerate(ep_col):
                if ep_val == episode_index:
                    # Found the row; extract all stats/* columns.
                    stats_cols = {
                        col: tbl.column(col).to_pylist()[row_idx]
                        for col in tbl.schema.names
                        if col.startswith("stats/")
                    }
                    return stats_cols if stats_cols else None

    return None


def _load_v2_episode_stats(ds: CanonicalDataset, episode_index: int) -> dict[str, object] | None:
    """Load per-episode stats for v2.1 from meta/episodes_stats.jsonl."""
    import json

    from trajlens.sources.paths import safe_join

    path = safe_join(ds.stats.root, "meta", "episodes_stats.jsonl")
    if not path.is_file():
        return None

    try:
        for line in path.read_text().splitlines():
            if not line.strip():
                continue
            record = json.loads(line)
            if record.get("episode_index") == episode_index:
                stats: dict[str, object] | None = record.get("stats")
                return stats
    except Exception:
        return None

    return None


PER_EPISODE_STATS_MATCH: Check = _PerEpisodeStatsMatchCheck()
registry.register(PER_EPISODE_STATS_MATCH)


# ---------------------------------------------------------------------------
# STATISTICAL.VALUE_SANITY
# ---------------------------------------------------------------------------
# Per-episode per-column variance and NaN scan.
# Severity escalation:
#   - all-NaN in a column over the episode  → FAIL
#   - all-zero across an episode            → WARN
#   - constant (zero variance) across ep    → WARN
#   - not all-NaN but NaN present           → WARN (partial NaN)
#
# FP note (per catalog): some features are legitimately constant, e.g. a
# fixed gripper during a reach.  We emit WARN, not FAIL, for constant features
# so the user can assess whether it's physically plausible.  Only all-NaN is
# FAIL because a column that is entirely NaN cannot contribute to training.

_VALUE_SANITY_COLUMNS = frozenset(
    {
        "observation.state",
        "action",
        "observation.effort",
        "observation.velocity",
    }
)


def _is_sanity_column(name: str) -> bool:
    """Return True for columns that should be checked for degenerate values."""
    if name in _VALUE_SANITY_COLUMNS:
        return True
    # Also catch columns that look like robot state/action by prefix.
    lower = name.lower()
    return (
        (lower.startswith("observation.") or lower.startswith("action") or lower == "action")
        and "image" not in lower
        and "video" not in lower
    )


class _ValueSanityCheck:
    id = "STATISTICAL.VALUE_SANITY"
    severity = Severity.WARN
    category = "STATISTICAL"
    requires_video = False
    thread_safe = True

    def run(self, ds: CanonicalDataset, ctx: CheckContext) -> CheckResult:
        resolver_handle = getattr(ds._resolver, "handle", None)
        if (
            not ctx.deep
            and resolver_handle is not None
            and getattr(resolver_handle, "repo_id", None) is not None
        ):
            return CheckResult(
                check_id=self.id,
                severity=Severity.INFO,
                message=(
                    "Skipped STATISTICAL.VALUE_SANITY for Hub dataset "
                    "(too slow over HTTP). Use --deep to verify stats."
                ),
            )

        fail_items: list[str] = []
        warn_items: list[str] = []

        target_features = [
            name
            for name, spec in ds.features.items()
            if spec.dtype not in ("video", "string") and _is_sanity_column(name)
        ]

        if not target_features:
            return CheckResult(
                check_id=self.id,
                severity=Severity.INFO,
                message="No state/action columns found to sanity-check.",
            )

        for episode in ds:
            pf = ds.parquet_shard_for_episode(episode)
            available = [f for f in target_features if f in pf.schema_arrow.names]
            if not available:
                continue

            table = pf.read(columns=["episode_index", *available])  # type: ignore[no-untyped-call]
            ep_col = table.column("episode_index").to_pylist()

            for feat_name in available:
                col = table.column(feat_name)
                col_list = col.to_pylist()
                ep_vals: list[float] = []

                for row_idx, ep_val in enumerate(ep_col):
                    if ep_val != episode.episode_index:
                        continue
                    raw = col_list[row_idx]
                    if isinstance(raw, list):
                        ep_vals.extend(float(x) if x is not None else math.nan for x in raw)
                    elif raw is None:
                        ep_vals.append(math.nan)
                    else:
                        ep_vals.append(float(raw))

                if not ep_vals:
                    continue

                nan_count = sum(1 for v in ep_vals if math.isnan(v))

                if nan_count == len(ep_vals):
                    fail_items.append(
                        f"episode {episode.episode_index} feature {feat_name!r}: "
                        f"all {len(ep_vals)} values are NaN"
                    )
                    continue

                if nan_count > 0:
                    warn_items.append(
                        f"episode {episode.episode_index} feature {feat_name!r}: "
                        f"{nan_count}/{len(ep_vals)} values are NaN"
                    )

                valid = [v for v in ep_vals if not math.isnan(v)]
                if not valid:
                    continue

                all_zero = all(v == 0.0 for v in valid)
                if all_zero:
                    warn_items.append(
                        f"episode {episode.episode_index} feature {feat_name!r}: "
                        f"all valid values are zero across the entire episode"
                    )
                    continue

                min_v = min(valid)
                max_v = max(valid)
                if min_v == max_v:
                    warn_items.append(
                        f"episode {episode.episode_index} feature {feat_name!r}: "
                        f"constant value {min_v:.6g} across the entire episode "
                        f"(may be physically implausible)"
                    )

            if len(fail_items) + len(warn_items) >= 20:
                break  # Cap output.

        if fail_items:
            # All-NaN is FAIL; warn items are also reported in details.
            return CheckResult(
                check_id=self.id,
                severity=Severity.FAIL,
                message=(
                    f"Value sanity FAIL — all-NaN column(s) found "
                    f"({len(fail_items)} instance(s)): {fail_items[0]}"
                ),
                details={"fail_items": fail_items, "warn_items": warn_items},
            )

        if warn_items:
            return CheckResult(
                check_id=self.id,
                severity=Severity.WARN,
                message=(
                    f"Value sanity warning — degenerate column(s) found "
                    f"({len(warn_items)} instance(s)): {warn_items[0]}"
                ),
                details={"warn_items": warn_items},
            )

        return CheckResult(
            check_id=self.id,
            severity=Severity.INFO,
            message="All state/action columns have non-degenerate values across episodes.",
        )


VALUE_SANITY: Check = _ValueSanityCheck()
registry.register(VALUE_SANITY)
